# Colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

# Screen dimensions
SCREEN_MAX_WIDTH = 700
SCREEN_MAX_HEIGHT = 500
SCREEN_SIZE = (SCREEN_MAX_WIDTH, SCREEN_MAX_HEIGHT)

# Fonts
FONT_TYPE = "monospace"
SCORE_FONT_SIZE = 30

# Game title
GAME_TITLE = "My very basic Pong game"

# Paddle
PADDLE_WIDTH = 10
PADDLE_HEIGHT = 90
# the initial X coord of the right paddle
RIGHT_PADDLE_X = SCREEN_MAX_WIDTH - PADDLE_WIDTH
LEFT_PADDLE_X = 0
PADDLE_Y = 200
PADDLE_MIN_Y = 0
PADDLE_MAX_Y = SCREEN_MAX_HEIGHT - PADDLE_HEIGHT
# the speed with which we move the paddle
PADDLE_SPEED = 5

# Ball constants
BALL_DIMENSION = 5
BALL_X = 10
BALL_MIN_X = 10
BALL_MAX_X = SCREEN_MAX_WIDTH - PADDLE_WIDTH
BALL_MIN_Y = 0
BALL_MAX_Y = SCREEN_MAX_HEIGHT - BALL_DIMENSION
BALL_INITIAL_Y_RANGE = [100, 350]
BALL_SPEED_X = BALL_SPEED_Y = 5

# Score
LEFT_SCORE_X = 370
RIGHT_SCORE_X = 300
SCORE_Y = 10

